### ISSUE TITLE
v1.5.0 seemingly not working with new short file header?

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/TeraConfig#13]
Using v1.5.0 of the Checkstyle config for the SplashScreen repo actually seems to fail on the new shortened header over some regex issue. Not spotting anywhere that version is in use yet - I wonder if it worked locally somewhere, depending on versions of something, but not in my case? 1.4.0 is fine though.

```
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Cannot set property 'header' to '(/*\n * Copyright 20\d\d MovingBlocks\n *\n * Licensed under the Apache License, Version 2.0)|(// Copyright 20\d\d The Terasology F
oundation\n// SPDX-License-Identifier: Apache-2.0)'
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.tryCopyProperty(AutomaticBean.java:237)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:191)
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:467)
        ... 113 more
Caused by: java.lang.reflect.InvocationTargetException
        at org.apache.commons.beanutils.PropertyUtilsBean.invokeMethod(PropertyUtilsBean.java:2128)
        at org.apache.commons.beanutils.PropertyUtilsBean.setSimpleProperty(PropertyUtilsBean.java:2109)
        at org.apache.commons.beanutils.BeanUtilsBean.copyProperty(BeanUtilsBean.java:437)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.tryCopyProperty(AutomaticBean.java:227)
        ... 115 more
Caused by: java.lang.IllegalArgumentException: line 1 in header specification is not a regular expression
        at com.puppycrawl.tools.checkstyle.checks.header.RegexpHeaderCheck.postProcessHeaderLines(RegexpHeaderCheck.java:336)
        at com.puppycrawl.tools.checkstyle.checks.header.AbstractHeaderCheck.loadHeader(AbstractHeaderCheck.java:171)
        at com.puppycrawl.tools.checkstyle.checks.header.AbstractHeaderCheck.setHeader(AbstractHeaderCheck.java:149)
        at com.puppycrawl.tools.checkstyle.checks.header.RegexpHeaderCheck.setHeader(RegexpHeaderCheck.java:359)
        ... 119 more
Caused by: java.util.regex.PatternSyntaxException: Unclosed group near index 3
(/*
   ^
        at com.puppycrawl.tools.checkstyle.checks.header.RegexpHeaderCheck.postProcessHeaderLines(RegexpHeaderCheck.java:331)
        ... 122 more
```

**Comment by skaldarnar** [comment]
@jdrueckert investigated the same for the launcher yesterday and found some issues with multi-line regex in Checkstyle I believe. I'll ping her for more info on this :nerd_face: 

https://github.com/MovingBlocks/TerasologyLauncher/pull/607 is failing because of this, I think.

**Comment by jdrueckert** [comment]
Yeah, so basically, we have the following situation:
1. `RegexpHeaderCheck` is not able to work with multiline regex expressions. It splits on every `\n` which is why alternation across multiple lines is not possible.
2. `RegexpCheck` is able to work with multiline regex expressions and can also act like `RegexpHeaderCheck` by using `\A` for the file beginning but for some reason doesn't identify alternation correctly, so it tries to match the whole expression (including the `|`).

@skaldarnar and I decided for the launcher to release a new version of `TeraConfig` that only checks for the new header and convert all headers to the new version.
Naturally for Terasology this will be considerably more effort, but we hope that with continous efforts across the whole game we'll eventually get to a point where we can also switch Terasology to use this new release :shrug:

**Comment by Cervator** [comment]
IMHO that's fine :-) We don't need to support the old header style at all. It'll temporarily spike the warnings (I figure?) but that's fine 👍

**Comment by skaldarnar** [comment]
> It'll temporarily spike the warnings (I figure?) but that's fine 👍

In case there are already warnings in a project that's likely not a huge deal. I'd like to avoid projects with no checkstyle warnings (I think the launcher is at least quite low on checkstyle warnings) to suddenly get a bunch, and then we (as developers) learn to ignore that number (because it's always high). 

On the other hand, might as well open up an Omega workspace, replace all the headers, and then push for the whole module space at once to get over with.
